#!/usr/bin/env bash
# Creating script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distributing requests using a roundrobin algorithm
# Making sure that HAProxy can be managed via an init script

# Installing and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend fosterlabs.tech_frontend
        bind *:80
        mode http
        default_backend fosterlabs.tech_backend
backend fosterlabs.tech_backend
        balance roundrobin
        server 423066-web-01 100.25.153.16:80 check
        server 423066-web-02 100.25.156.205:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
